import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Chat.module.css";

const Chat: NextPage = () => {
  const { container } = styles;
  return (
    <div className={container}>
      <Head>
        <title>Whatsapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Chat;
