import type { NextPage } from "next";
import Head from "next/head";
import Sidebar from "../components/sidebar/Sidebar";
import styles from "../styles/Home.module.css";
const Home: NextPage = () => {
  const { container } = styles;
  return (
    <div className={container}>
      <Head>
        <title>Whatsapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar />
    </div>
  );
};

export default Home;
